### ISSUE TITLE
Configure repository settings

### ISSUE THREAD

**Issue by Plytas** [gtmassey/laravel-analytics#8]
Couple things to consider here:
* Using only `main` branch and making PRs to it. That's the most common approach in the wild. We can take example from Spatie.
* Lock direct pushes to main branch, only through PRs.
* Disable PR merge without reviews/successful actions.
* Use `Squash and merge` strategy for PRs.

**Comment by gtmassey** [comment]
1. Main branch now restricts pushes, must use PR.
2. Dev branch is merged to main and deleted. 
3. I need to check into reviews/successful actions, open to ideas though. Maybe auto run the tests and make sure that a certain set of them always pass before allowing PR merge?

**Comment by Plytas** [comment]
I'm gonna re-open this, because I think we can do better with the settings. Right now there's nothing preventing us from merging failing and unreviewed PRs.
<img width="413" alt="image" src="https://user-images.githubusercontent.com/17316322/204552507-ae488aea-9f92-4031-9ef8-67c5fa76715e.png">

I'd be happy to set it up if you give me permissions.
